import { type NextPage } from "next";
import Head from "next/head";
import AppCard from "~/components/AppCard";
import Title from "~/components/Title";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Private network playground</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/private-networking.svg" color="#ffffff" />
      </Head>

      <main
        className="flex h-screen min-h-0 flex-col items-center py-8"
        style={{
          backgroundImage: `linear-gradient(
            140deg,
            hsl(240deg 46% 37%) 0%,
            hsl(280deg 49% 38%) 36%,
            hsl(311deg 56% 41%) 59%,
            hsl(328deg 63% 50%) 76%,
            hsl(342deg 87% 59%) 87%,
            hsl(358deg 100% 67%) 94%,
            hsl(17deg 100% 64%) 99%,
            hsl(33deg 100% 59%) 101%,
            hsl(46deg 100% 51%) 101%,
            hsl(55deg 100% 50%) 100%
        );`,
        }}
      >
        <div className="flex h-full min-h-0 w-full flex-col items-center justify-center gap-2 gap-y-8">
          <Title />

          <div className="flex grid h-full w-full grid-cols-2 gap-10 px-8">
            {([0, 1, 2, 3] as (0 | 1 | 2 | 3)[]).map(
              (appIdx: 0 | 1 | 2 | 3) => (
                <AppCard appIdx={appIdx} key={appIdx} />
              )
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
